experiment: "mini_test_01"
s
data_dir: "mydata/dac-train"
data_frames: "mydata/dac-train.xlsx"
validator_data_dir: "mydata/dac-val"
validator_data_frames: "mydata/dac-val.xlsx"


TransformerClass: "RopeCondDACTransformer" 
vocab_size: 1024
num_tokens: 4

cond_params: 1 #1 (not counting the classes)
model_size: 512 # must be divisible by num_heads
# tblock_input_size: 35 #512  #embedding+conditioning vect

Ti: 86 # 172 #86
Tt: 295 # must match the length of the sequences in the batch
batch_size: 8  #**


num_layers: 4 #**
num_heads: 8 #8 # 8 # embed_size must be divisible by num_heads
forward_expansion: 4 #4 #4
dropout_rate: 0.2
learning_rate: 0.001

num_epochs: 500 ### 800 

ErrorLogRate: 2 #2 ### 10
checkpoint_interval: 5 ###50 # 25

